# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'RBLSiri.p12'
    certPwd: '123456789'

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: '- task: Xcode@5

- task: Xcode@5
  inputs:
    actions: 'build'
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    provisioningProfileName: 'RBLSiri.mobileprovision'
    destinationPlatformOption: 'iOS'